version: "3.7"

networks:
  nginx-proxy-manager_default:
    external: true

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080
  
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 6969:80
    depends_on:
      - flask

