version: "3.7"

networks:
  scoobydoo:

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080
    networks:
      - scoobydoo
  
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    depends_on:
      - flask
    networks:
      - scoobydoo

