version: "3.7"

networks:
  nginx-proxy-manager_default:
    external: true

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
      - DB_USERNAME=example
    expose:
      - 8080
    networks:
      - nginx-proxy-manager_default
        
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    depends_on:
      - flask
    networks:
      - nginx-proxy-manager_default

