version: "3.7"

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080
  
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    networks:
      - nginx-proxy-manager_default
    ports:
      - 80:80
    depends_on:
      - flask